// Motivational quotes about productivity and not wasting time
const PRODUCTIVITY_QUOTES = [
  { text: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", author: "Stephen Covey" },
  { text: "Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort.", author: "Paul J. Meyer" },
  { text: "Until we can manage time, we can manage nothing else.", author: "Peter Drucker" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Don't confuse activity with productivity. Many people are simply busy being busy.", author: "Robin Sharma" },
  { text: "Your mind is for having ideas, not holding them.", author: "David Allen" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "It's not always that we need to do more but rather that we need to focus on less.", author: "Nathan W. Morris" },
  { text: "The biggest time waste is doing well what need not be done at all.", author: "Bruce Lee" },
  { text: "Simplicity boils down to two steps: Identify the essential. Eliminate the rest.", author: "Leo Babauta" },
  { text: "Productivity is being able to do things that you were never able to do before.", author: "Franz Kafka" },
  { text: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Bruce Lee" },
  { text: "Time is what we want most, but what we use worst.", author: "William Penn" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King" },
  { text: "You don't need more time, you just need to decide.", author: "Seth Godin" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "The perfect is the enemy of the good.", author: "Voltaire" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
  { text: "You may delay, but time will not.", author: "Benjamin Franklin" },
  { text: "The only thing to do with good advice is to pass it on. It is never of any use to oneself.", author: "Oscar Wilde" },
  { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "The difference between successful people and very successful people is that very successful people say 'no' to almost everything.", author: "Warren Buffett" },
  { text: "There is nothing so useless as doing efficiently that which should not be done at all.", author: "Peter Drucker" },
  { text: "What you stay focused on will grow.", author: "Roy T. Bennett" },
  { text: "The more time you spend contemplating what you should have done, the less time you have to do what you should be doing.", author: "Guilt Freud" },
  { text: "Never mistake motion for action.", author: "Ernest Hemingway" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Albert Einstein" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "The best way to have a good idea is to have a lot of ideas.", author: "Linus Pauling" },
  { text: "You can have it all. Just not all at once.", author: "Oprah Winfrey" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "If you don't pay appropriate attention to what has your attention, it will take more of your attention than it deserves.", author: "David Allen" },
  { text: "Ordinary people think merely of spending time, great people think of using it.", author: "Arthur Schopenhauer" },
  { text: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", author: "Socrates" },
  { text: "You can't change how people treat you or what they say about you. All you can change is how you react to it.", author: "Mahatma Gandhi" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", author: "Henry Ford" },
  { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" }
];

// Function to get a random quote
function getRandomQuote() {
  const randomIndex = Math.floor(Math.random() * PRODUCTIVITY_QUOTES.length);
  return PRODUCTIVITY_QUOTES[randomIndex];
} 